export const SENTENCES = [
  [ 'NOUNS', 'ADVERBS', 'VERBS', 'ADJECTIVES', 'PREPOSITIONS', 'NOUNS' ],
  [ 'PRONOUNS', 'NOUNS', 'ADVERBS', 'PRONOUNS', 'ADJECTIVES', 'VERBS', 'ARTICLES', 'NOUNS', 'VERBS', 'NOUNS' ],
  [ 'ADVERBS', 'ARTICLES', 'VERBS', 'ADJECTIVES', ',', 'PRONOUNS', 'VERBS', 'ADVERBS', 'VERBS' ],
  [ 'INTERJECTIONS', '!', 'ARTICLES', 'PREPOSITIONS', 'ADJECTIVES', 'ADJECTIVES', 'ADJECTIVES', 'NOUNS', 'ADVERBS', 'VERBS' ],
  [ 'ARTICLES', 'VERBS', 'ARTICLES', 'NOUNS', 'VERBS', 'PREPOSITIONS', 'ARTICLES', ',', 'NOUNS', 'ADJECTIVES', 'PREPOSITIONS', 'NOUNS', 'ADVERBS', 'NOUNS', ',', 'ADVERBS', 'ADJECTIVES' ],
];
